
<script>


export default {
    "PLUGINS_WORKSPACES_LANGUAGE_CODE": "fr",

    "RIBBON_TABS_TAB_PROJECTS_WORKSPACE_LABEL": "Espaces projets",
    "RIBBON_TABS_TAB_PROJECTS_LABEL": "Projets",
    "RIBBON_TABS_TAB_PROJECTS_GROUP_PROJECT_LABEL": "Projet",
    "RIBBON_TABS_TAB_PROJECTS_GROUP_SITE_LABEL": "Site associé",
    "RIBBON_TABS_TAB_PROJECTS_GROUP_CATEGORY_LABEL": "Thématique",
    "RIBBON_TABS_TAB_PROJECTS_GROUP_TAGS_LABEL": "Gestion",
    "PLUGINS_WORKSPACES_RIBBON_TABS_TAB_TAGS_LABEL": "Etiquettes des espaces projets",
    "PLUGINS_WORKSPACES_RIBBON_TABS_TAB_CATEGORIES_LABEL": "Thématiques des espaces projets",
    "PLUGINS_WORKSPACES_RIBBON_TABS_TAB_KEYWORDS_LABEL": "Mots-clés des espaces projets",

    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CATEGORY": "Administration des espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CREATE_PRIVATE_LABEL": "Créer un projet privé",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CREATE_PRIVATE_DESCRIPTION": "Autorise à créer un nouvel espace projet privé sur invitation uniquement",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CREATE_PUBLIC_MODERATED_LABEL": "Créer un projet public avec inscription",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CREATE_PUBLIC_MODERATED_DESCRIPTION": "Autorise à créer un nouvel espace projet public avec inscriptions modérées par le(s) responsable(s)",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CREATE_PUBLIC_OPENED_LABEL": "Créer un projet public",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_CREATE_PUBLIC_OPENED_DESCRIPTION": "Autorise à créer un nouvel espace projet public ouvert à tous les utilisateurs de la plateforme",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_EDIT_LABEL": "Modifier un projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_EDIT_DESCRIPTION": "Autorise à modifier les propriétés d'un espace projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_DELETE_LABEL": "Supprimer un projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_DELETE_DESCRIPTION": "Autorise à supprimer un espace projet",
    "PLUGINS_WORKSPACES_RIGHTS_TAGS_HANDLE_TAG_LABEL": "Gérer les étiquettes projets",
    "PLUGINS_WORKSPACES_RIGHTS_TAGS_HANDLE_TAG_DESCRIPTION": "Autorise de gérer les étiquettes projets",
    "PLUGINS_WORKSPACES_RIGHTS_CATEGORIES_HANDLE_CATEGORY_LABEL": "Gérer les thématiques de projet",
    "PLUGINS_WORKSPACES_RIGHTS_CATEGORIES_HANDLE_CATEGORY_DESCRIPTION": "Autorise de gérer les thématiques de projet",
    "PLUGINS_WORKSPACES_RIGHTS_KEYWORDS_HANDLE_KEYWORD_LABEL": "Gérer les mots-clés des projets",
    "PLUGINS_WORKSPACES_RIGHTS_KEYWORDS_HANDLE_KEYWORD_DESCRIPTION": "Autorise de gérer les mots-clés des projets",

    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_DOCUMENT_MAIL_NOTIFICATION_LABEL": "Recevoir les notifications sur les documents",
	"PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_DOCUMENT_MAIL_NOTIFICATION_DESCRIPTION": "Autorise à recevoir par mail les notifications concernant les documents des espaces projets.",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_THREAD_MAIL_NOTIFICATION_LABEL": "Recevoir les notifications sur les fils de discussion",
	"PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_THREAD_MAIL_NOTIFICATION_DESCRIPTION": "Autorise à recevoir par mail les notifications concernant les fils de discussion des espaces projets.",

    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_CATEGORY": "Création de services des espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_TASK_LIST_SIMPLE_LABEL": "Tâches (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_TASK_LIST_SIMPLE_DESCRIPTION": "Droit de créer le service listant des tâches des espaces projets (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_EVENTS_LABEL": "Calendrier des espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_EVENTS_DESCRIPTION": "Droit de créer le service calendrier des espaces projets.",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_EVENTS_SIMPLE_LABEL": "Calendrier des espaces projets (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_EVENTS_SIMPLE_DESCRIPTION": "Droit de créer le service calendrier des espaces projets (simple).",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_PROJECTS_CATALOG_LABEL": "Catalogue des espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_PROJECTS_CATALOG_DESCRIPTION": "Droit de créer le service des catalogues des espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_PROJECTS_CATALOG_SIMPLE_LABEL": "Catalogue des espaces projets (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_PROJECTS_CATALOG_SIMPLE_DESCRIPTION": "Droit de créer le service des catalogues des espaces projets (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_ACTIVITY_STREAM_LABEL": "Flux d'activités",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_ACTIVITY_STREAM_DESCRIPTION": "Droit de créer le service des flux d'activités des espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_ACTIVITY_STREAM_SIMPLE_LABEL": "Flux d'activités (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_ACTIVITY_STREAM_SIMPLE_DESCRIPTION": "Droit de créer le service des flux d'activités des espaces projets (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_DOCUMENTS_SIMPLE_LABEL": "Flux de documents (simple)",
    "PLUGINS_WORKSPACES_RIGHTS_SERVICE_DOCUMENTS_SIMPLE_DESCRIPTION": "Droit de créer le service listant les derniers documents ajoutés et modifiés (simple)",

    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_CATEGORY": "Espaces projets",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_MEMBERS_LABEL": "Module Membres du projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_MEMBERS_DESCRIPTION": "Autorise l'ajout du module permettant de visualiser et gérer les membres d'un espace projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_MEMBERS_ADD_LABEL": "Ajouter un membre",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_MEMBERS_ADD_DESCRIPTION": "Autorise l'ajout et la modification d'un membre du projet.",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_MEMBERS_REMOVE_LABEL": "Supprimer un membre",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_MEMBERS_REMOVE_DESCRIPTION": "Autorise la suppression d'un membre du projet.",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_DOCUMENT_LABEL": "Module Documents",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_DOCUMENT_DESCRIPTION": "Autorise l'ajout du module permettant de visualiser et contribuer aux documents d'un espace projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_CALENDAR_LABEL": "Module Calendriers",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_CALENDAR_DESCRIPTION": "Autorise l'ajout du module permettant de visualiser et contribuer aux calendriers d'un espace projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_THREAD_LABEL": "Module Fils de discussion",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_THREAD_DESCRIPTION": "Autorise l'ajout du module permettant de visualiser et contribuer aux fils de discussion d'un espace projet",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_TASK_LABEL": "Module Tâches",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_TASK_DESCRIPTION": "Autorise l'ajout du service tâches.",

    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_ADD_TAGS_LABEL": "Créer une étiquette",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_ADD_TAGS_DESCRIPTION": "Permet de créer de nouvelles étiquettes utilisables par tous les calendriers",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_DELETE_TAGS_LABEL": "Supprimer une étiquette",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_DELETE_TAGS_DESCRIPTION": "Permet de supprimer une étiquette utilisée par les calendriers",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_ADD_PLACE_LABEL": "Créer un lieu",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_ADD_PLACE_DESCRIPTION": "Permet de créer un lieu qui pourra être associé aux évènements des calendriers",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_DELETE_PLACE_LABEL": "Supprimer un lieu",
    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_SERVICE_DELETE_PLACE_DESCRIPTION": "Permet de supprimer un lieu associé aux évènements des calendriers",

    "PLUGINS_WORKSPACES_RIGHTS_CREATE_CONTENT_ABOUT_LABEL": "Créer un contenu A propos",
    "PLUGINS_WORKSPACES_RIGHTS_CREATE_CONTENT_ABOUT_DESCRIPTION": "Autorise la création de contenu destinés au module A propos. Ces contenus sont normalement auto-générés par le module",

    "PLUGINS_WORKSPACES_RIGHTS_PROJECT_MODULE_ABOUT_CATEGORY": "Module A propos",

    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_CATEGORY_CALENDAR": "Espaces projets - Calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_ADD_CALENDAR_LABEL": "Ajouter un calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_EDIT_CALENDAR_LABEL": "Modifier un calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_DELETE_CALENDAR_LABEL": "Supprimer un calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_ADD_CALENDAR_DESCRIPTION": "Autorise à ajouter un calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_EDIT_CALENDAR_DESCRIPTION": "Autorise à modifier un calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_DELETE_CALENDAR_DESCRIPTION": "Autorise à supprimer un calendrier",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_HANDLE_RESOURCE_LABEL": "Gérer les ressources",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_BOOK_RESOURCE_LABEL": "Réserver les ressources",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_HANDLE_RESOURCE_DESCRIPTION": "Autorise à ajouter, modifier, supprimer, ou réserver en direct des ressources",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_BOOK_RESOURCE_DESCRIPTION": "Autorise à réserver des ressources dans un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_ADD_EVENT_LABEL": "Ajouter un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_EDIT_EVENT_LABEL": "Modifier un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_DELETE_EVENT_LABEL": "Supprimer n'importe quel évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_DELETE_OWNED_EVENT_LABEL": "Supprimer ses évènements uniquement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_PROPOSE_EVENT_LABEL": "Proposer un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_VALIDATE_EVENT_LABEL": "Valider un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_REFUSE_EVENT_LABEL": "Refuser un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_ADD_EVENT_DESCRIPTION": "Autorise à ajouter un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_EDIT_EVENT_DESCRIPTION": "Autorise à modifier un évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_DELETE_EVENT_DESCRIPTION": "Autorise à supprimer n'importe quel évènement",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_DELETE_OWNED_EVENT_DESCRIPTION": "Autorise l'utilisateur à supprimer uniquement ses propres évènements",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_PROPOSE_EVENT_DESCRIPTION": "Proposer un évènement si le cycle de vie associé le permet",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_VALIDATE_EVENT_DESCRIPTION": "Valider un évènement si le cycle de vie associé le permet",
    "PLUGINS_WORKSPACES_RIGHTS_WORKSPACES_REFUSE_EVENT_DESCRIPTION": "Refuser un évènement si le cycle de vie associé le permet",

    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY": "Espaces projets",

    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_RIGHTS_GROUP": "Gestion des droits",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_LIST": "Profils disponibles",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_LIST_DESC": "Liste des profils spécifique à la gestion des droits des membres des espaces projets. La valeur doit être la liste des identifiants des profils séparés par des virgules.",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_LIST_INVALID": "La valeur doit être la liste des identifiants des profils séparés par des virgules.",

    "PLUGINS_WORKSPACES_PARAM_PROFILE_DEFAULT": "Profil par défaut des membres",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_DEFAULT_DESC": "Identifiant du profil qui sera affecté par défaut aux nouveaux membres.",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_DEFAULT_INVALID": "La valeur doit être un identifiant de profil.",

    "PLUGINS_WORKSPACES_PARAM_PROFILE_MANAGERDEFAULT": "Profil par défaut des responsables",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_MANAGERDEFAULT_DESC": "Identifiant du profil qui sera affecté par défaut aux nouveaux responsables.",
    "PLUGINS_WORKSPACES_PARAM_PROFILE_MANAGERDEFAULT_INVALID": "La valeur doit être un identifiant de profil.",

    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_NOTIFICATIONS_GROUP": "Notifications des membres",

    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_ONLYOFFICE_GROUP": "OnlyOffice",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_ENABLED": "Activer OnlyOffice",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_ENABLED_DESCRIPTION": "Lorsque OnlyOffice est activé, les miniatures et les prévisualisations des fichiers sont automatiquement gérées par OnlyOffice.",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_SERVER_URL": "URL du server OnlyOffice",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_SERVER_URL_DESCRIPTION": "URL d'accès au serveur OnlyOffice. Lorsque OnlyOffice est activé, les miniatures et les prévisualisations des fichiers sont automatiquement gérées par OnlyOffice.",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_BO_URL": "Adresse interne du back-office",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_BO_URL_DESCRIPTION": "Vous pouvez préciser dans ce champ une adresse différente de l'adresse rentrée dans le paramètre de configuration &lt;i&gt;CMS > Paramètres de l'application CMS > Adresse du back-office&lt;/i&gt;. Cette adresse est l'adresse utilisée par le serveur OnlyOffice pour requêter Ametys.&lt;br/&gt;Ce paramètre peut demeurer vide pour utiliser la même adresse.",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_SECRET": "Clef secrète",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_SECRET_DESCRIPTION": "Précisez la clef secrète du serveur OnlyOffice pour signer les requêtes",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_ENABLED_EDITION": "Activer la modification",
    "PLUGINS_WORKSPACES_PARAM_ONLYOFFICE_ENABLED_EDITION_DESCRIPTION": "Activer la modification via OnlyOffice",

    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_PARAM_MSOFFICE_GROUP": "Modification WebDAV",
    "PLUGINS_WORKSPACES_PARAM_MSOFFICE_ENABLED": "Activer la modification WebDAV",
    "PLUGINS_WORKSPACES_PARAM_MSOFFICE_ENABLED_DESCRIPTION": "Activer la modification sur l'ordinateur via WebDAV.",

    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_PERIODIC_NOTIFICATIONS_GROUP": "Notifications périodiques",
    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_PERIODIC_NOTIFICATIONS_SCHEDULER_HOUR_LABEL": "Heure d'envoi",
    "PLUGINS_WORKSPACES_PARAM_MAIN_CATEGORY_PERIODIC_NOTIFICATIONS_SCHEDULER_HOUR_DESCRIPTION": "Heure d'envoi des mails quotidiens, hebdomadaires ou mensuels pour le résumé d'activité",

    "PLUGINS_WORKSPACES_CALENDAR_PARAM_CATEGORY": "Calendriers",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_GROUP": "Affichage par défaut",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_TYPE_LABEL": "Vue par défaut",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_TYPE_DESC": "Choix de la vue par défaut",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_TYPE_MONTH": "Mois",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_TYPE_WEEK": "Semaine",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_TYPE_DAY": "Jour",

    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_MODE_LABEL": "Mode de vue par défaut",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_MODE_DESC": "Choix du mode de vue par défaut",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_MODE_AGENDA": "Agenda",
    "PLUGINS_WORKSPACES_CALENDAR_PARAM_VIEW_MODE_LIST": "Liste",

    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_GROUP": "Evènements",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_LABEL": "Jours ouvrés",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_DESC": "Liste des jours ouvrés de la semaine.",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_MONDAY": "Lundi",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_TUESDAY": "Mardi",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_WEDNESDAY": "Mercredi",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_THURSDAY": "Jeudi",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_FRIDAY": "Vendredi",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_SATURDAY": "Samedi",
    "PLUGINS_WORKSPACES_CALENDAR_EVENT_PARAM_WORKING_DAY_SUNDAY": "Dimanche",

    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_LABEL": "Espace projet",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_DESCRIPTION": "Type de site spécialisé pour les espaces projets. L'accès au site et à ses ressources et restreint par défaut.",

    "PLUGINS_WORKSPACES_CACHE_PROJECT_MANAGER_LABEL": "Espaces projets / Projets par site",
    "PLUGINS_WORKSPACES_CACHE_PROJECT_MANAGER_DESCRIPTION": "Liste des projets associés à un site",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_UUID_CACHE_LABEL": "Espaces projets / Identifiants",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_UUID_CACHE_DESCRIPTION": "Association entre un nom de projet et son identifiant unique UUID. Compte tenu de son utilisation, le ratio affiché n'est pas représentatif de l'efficacité du cache",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_REQUEST_CACHE_LABEL": "Espaces projets / Objets",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_REQUEST_CACHE_DESCRIPTION": "Association entre un nom de projet et l'objet Projet",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_PAGEREQUEST_CACHE_LABEL": "Espaces projets / Pages par module",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_PAGEREQUEST_CACHE_DESCRIPTION": "Association entre un nom de projet et un nom de module et l'objet Page",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_PAGEUUID_CACHE_LABEL": "Espace projets / Identifiants des pages de module",
    "PLUGINS_WORKSPACES_PROJECT_MANAGER_PAGEUUID_CACHE_DESCRIPTION": "Association entre un nom de projet, une langue et un nom de module et la liste de pages de modules",

    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULES_TAG_CATEGORY": "Espaces projets",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULES_TAG_CATEGORY_DESC": "Etiquettes spécifiques aux pages contenant un module d'un espace projet.",
	"PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_DOCUMENT_PAGE_TAG": "Fichiers",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_DOCUMENT_PAGE_TAG_DESC": "Page de référence pour le module fichiers.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_CALENDAR_PAGE_TAG": "Calendrier",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_CALENDAR_PAGE_TAG_DESC": "Page de référence pour le module calendrier.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_THREAD_PAGE_TAG": "Fil de discussion",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_THREAD_PAGE_TAG_DESC": "Page de référence pour le module fil de discussion.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_TASK_PAGE_TAG": "Tâches",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_TASK_PAGE_TAG_DESC": "Page de référence pour le module tâches.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_ABOUT_PAGE_TAG": "A propos",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_ABOUT_PAGE_TAG_DESC": "Page de référence pour le module A propos.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_MEMBERS_PAGE_TAG": "Membres",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_MEMBERS_PAGE_TAG_DESC": "Page de référence pour la gestion des membres du projet.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_NEWS_PAGE_TAG": "Actualités",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_NEWS_PAGE_TAG_DESC": "Page de référence pour la gestion des actualités projet.",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_ALERTS_PAGE_TAG": "Alertes",
    "PLUGINS_WORKSPACES_PROJECT_TAGS_MODULE_ALERTS_PAGE_TAG_DESC": "Page de référence pour la gestion des alertes projet.",

    "PLUGINS_WORKSPACES_DAOS_PROJECT_ERROR": "Une erreur a empêché de retrouver les informations du projet",
    "PLUGINS_WORKSPACES_DAOS_PROJECT_NOT_FOUND": "Projet non trouvé",
    "PLUGINS_WORKSPACES_DAOS_PROJECT_NOT_FOUND_HINT": "Le projet n'a pas été trouvé. Veuillez vous assurer que le site de ce projet n'a pas été supprimé.",

    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_LABEL": "Espaces projets",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_DESCRIPTION": "Gestion des espaces projets",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_TITLE": "Titre",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_NAME": "Identifiant technique",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_DESCRIPTION": "Description",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_CREATION": "Date de création",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_CATEGORIES": "Thématiques",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_TAGS": "Etiquettes",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_COLUMN_MANAGERS": "Responsables",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_FILTER_EMPTY_TEXT": "Filtre (3 caractères minimun)",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_FILTER_CLEAR": "Effacer le filtre",
    "PLUGINS_WORKSPACES_PROJECT_LIST_TOOL_FILTER_MIN_LENGTH_INVALID": "Le filtre de recherche doit contenir au moins 3 caractères",

    "PLUGINS_WORKSPACES_PROJECT_NO_VALID_DESCRIPTION": "Ce bouton est désactivé car aucun project n'est sélectionné ou que la configuration de l'espace projet est incomplète.",

    "PLUGINS_WORKSPACES_PROJECT_ADD_PROJECT_LABEL": "Nouveau projet",
    "PLUGINS_WORKSPACES_PROJECT_ADD_PROJECT_DESCRIPTION": "Crée un nouvel espace projet pour l'intranet collaboratif",
    "PLUGINS_WORKSPACES_PROJECT_ADD_PROJECT_ERROR": "Erreur lors de la création du projet",
    "PLUGINS_WORKSPACES_PROJECT_ADD_PROJECT_ERROR_SITE_NOT_FOUND": "Impossible de retrouver les informations sur le site de l'espace projet.",
    "PLUGINS_WORKSPACES_PROJECT_EDIT_PROJECT_LABEL": "Modifier",
    "PLUGINS_WORKSPACES_PROJECT_EDIT_PROJECT_DESCRIPTION": "Modifier les propriétés du projet sélectionné.",
    "PLUGINS_WORKSPACES_PROJECT_SEE_SITE_LABEL": "Site",
    "PLUGINS_WORKSPACES_PROJECT_SEE_SITE_DESCRIPTION": "Accès à l'écran de gestion du site associé",
    "PLUGINS_WORKSPACES_PROJECT_CONFIG_SITE_LABEL": "Configuration du site",
    "PLUGINS_WORKSPACES_PROJECT_CONFIG_SITE_DESCRIPTION": "Configuration du site de l'espace projet sélectionné.",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_PROJECT_LABEL": "Supprimer",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_PROJECT_DESCRIPTION": "Supprimer défintivement le projet. Le site de l'espace projet sera aussi supprimé.",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_PROJECT_DIALOG_TITLE": "Supprimer le projet",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_PROJECT_DIALOG_CONFIRM": "Etes-vous sûr de vouloir supprimer ce ou ces projets? Cela supprimera aussi l'ensemble des projets compris dans la sous-arborescence, ainsi que les sites des espaces projets correspondants.",

    "PLUGINS_WORKSPACES_PROJECT_OPEN_PROJECT_WORKSPACE_LABEL": "Accéder au projet",
    "PLUGINS_WORKSPACES_PROJECT_OPEN_PROJECT_WORKSPACE_DESCRIPTION": "Ouvre le site de l'espace projet correspondant",
    "PLUGINS_WORKSPACES_PROJECT_OPEN_PROJECT_WORKSPACE_ERROR": "Impossible accéder l'espace projet.",
    "PLUGINS_WORKSPACES_PROJECT_OPEN_PROJECT_WORKSPACE_ERROR_SITE_NOT_FOUND": "L'espace projet correspondant n'a pas été trouvé. Veuillez vous assurer que le site de ce projet n'a pas été supprimé.",
    "PLUGINS_WORKSPACES_PROJECT_OPEN_PROJECT_WORKSPACE_ERROR_NOT_VALID": "La configuration de l'espace projet est incomplète. Veuillez configurer le site correspondant à cet espace projet avant de pouvoir effectuer cette opération.",

    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_LABEL": "Choisir le responsable",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_DESCRIPTION": "Permet de choisir le responsable de l'espace projet. Cette action remplacera l'ancien responsable mais ne lui retirera PAS ses droits d'accès.",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_TITLE": "Affecter un gestionnaire",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_SUCCESS": "L'affectation a été effectuée.",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_ERROR": "Affectation impossible",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_ERROR_SITE_NOT_FOUND": "L'espace projet correspondant n'a pas été trouvé. Veuillez vous assurer que le site de ce projet n'a pas été supprimé.",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_ERROR_NOT_VALID": "La configuration de l'espace projet est incomplète. Veuillez configurer le site correspondant à cet espace projet avant de pouvoir effectuer cette opération.",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_ERROR_MISC": "Une erreur est survenue. Impossible d'affecter ce ou ces utilisateurs.",
    "PLUGINS_WORKSPACES_PROJECT_AFFECT_SUPERUSER_NO_POPULATION_DESCRIPTION": "Votre application ne possède pas de population d'utilisateurs autorisée. Veuillez choisir une population d'utilisateurs autorisée à accéder à l'espace projet avant de pouvoir continuer.",

    "PLUGINS_WORKSPACES_PROJECT_DEFAULT_PROJECT_WORKSPACE_TITLE": "Espace projet - {0}",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_INDEX_TITLE": "Accueil",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_NEWS_TITLE": "Actualités",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_ALERTS_TITLE": "Alertes",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_INDEX_MODULE_USERS_TITLE": "Liste des membres",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_INDEX_ACTIVITY_STREAM_TITLE": "Flux d'activités",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_CALENDARS_TITLE": "Calendrier",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_DOCUMENTS_TITLE": "Fichiers",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_FORUM_TITLE": "Forum",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_TASKS_TITLE": "Tâches",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_MINISITE_TITLE": "Mini-site",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_ABOUT_TITLE": "A propos",
    "PLUGINS_WORKSPACES_PROJECT_WORKSPACE_PAGE_MEMBERS_TITLE": "Membres",

    "PLUGINS_WORKSPACES_PROJECT_EDIT_DIALOG_TITLE": "Modifier le projet",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_DIALOG_TITLE": "Créer un projet",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_DIALOG_HELP_TEXT": "La première étape consiste à renseigner quelques informations générales sur le projet à créer.&lt;br/&gt;Le titre et le nom du projet sont des champs obligatoires.",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_DIALOG_HELP_TEXT_NAME": "Le nom du projet est un identifiant technique servant principalement aux stockage des données liées à l'espace projet.&lt;br/&gt;Le nom est automatiquement généré à partir du titre, il n'est donc pas nécessaire de le modifier sans raison particulière.",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_DIALOG_FORM_NAME": "Nom",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_DIALOG_FORM_NAME_DESC": "Nom du projet",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_DIALOG_FORM_NAME_REGEX_ERROR": "Les caractères autorisés sont les lettres, les chiffres, les tirets bas ou haut et les points. Le premier caractère doit obligatoirement être une lettre.",
    "PLUGINS_WORKSPACES_PROJECT_EDIT_DIALOG_SITE_CONFIG_HELP_TEXT": "Cliquez sur ce lien pour ouvrir l'outil de configuration du site de l'espace projet &lt;em&gt;{title}&lt;/em&gt; et modifier les paramètres associés.",

    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_HELP_TEXT_TITLE": "Le titre est l'intitulé principal de votre projet.",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_TITLE": "Titre",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_TITLE_DESC": "Intitulé principal du projet",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_TITLE_REGEX_ERROR": "Le titre doit contenir au moins une lettre et doit commencer par une lettre, un chiffre ou les caractères spéciaux suivants: - _",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_DESCRIPTION": "Description",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_DESCRIPTION_DESC": "Brève description du projet",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_MAILING_LIST": "Liste de diffusion",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_FORM_MAILING_LIST_DESC": "Liste de diffusion de l'espace projet",
    "PLUGINS_WORKSPACES_PROJECT_INSCRIPTION_STATUS_FORM_NAME": "Inscription",
    "PLUGINS_WORKSPACES_PROJECT_INSCRIPTION_STATUS_FORM_NAME_DESC": "Niveau d'inscription au projet. Le niveau d'inscription définit comment un utilisateur peut devenir membre du projet:&lt;br/&gt;- ouverte: inscription automatique&lt;br/&gt;- modérée: l'inscription nécessite l'approbation du gestionnaire du projet&lt;br/&gt;- privée: inscription non autorisée",
    "PLUGINS_WORKSPACES_PROJECT_INSCRIPTION_STATUS_ENUM_OPEN": "Ouverte",
    "PLUGINS_WORKSPACES_PROJECT_INSCRIPTION_STATUS_ENUM_MODERATED": "Modérée",
    "PLUGINS_WORKSPACES_PROJECT_INSCRIPTION_STATUS_ENUM_PRIVATE": "Privée",
    "PLUGINS_WORKSPACES_PROJECT_DEFAULT_PROFILE_FORM_NAME": "Profil par défaut à l'inscription",
    "PLUGINS_WORKSPACES_PROJECT_DEFAULT_PROFILE_FORM_NAME_DESC": "Profil attribué par défaut aux nouveaux membres du projet lorsque les inscriptions sont ouvertes.",

    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_OK": "Ok",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_DIALOG_CANCEL": "Annuler",

    "PLUGINS_WORKSPACES_PROJECT_EDITION_ERROR_CONFIGURATION": "Opération impossible",
    "PLUGINS_WORKSPACES_PROJECT_EDITION_ERROR_CONFIGURATION_INCOMPLETE": "Erreur inattendue, les données de configuration sont incomplètes.",

    "PLUGINS_WORKSPACES_PROJECT_CREATE_ERROR": "Création impossible",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_ERROR_PROJECT_EXISTS": "Un projet possédant le même nom existe déjà. Veuillez modifier le nom du projet à créer.",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_ERROR_NAME_EXISTS": "Une thématique de même niveau ayant le même nom existe déjà. Veuillez modifier le nom du projet à créer.",

    "PLUGINS_WORKSPACES_PROJECT_CREATE_CONFIRM": "Confirmation",
    "PLUGINS_WORKSPACES_PROJECT_CREATE_CONFIRM_MESSAGE": "Vous allez être redirigé vers la configuration du site de l'espace projet.&lt;br/&gt;Veillez à compléter cette configuration pour finaliser la création de votre espace projet.",

    "PLUGINS_WORKSPACES_PROJECT_ADD_CATEGORY_LABEL": "Nouvelle thématique",
    "PLUGINS_WORKSPACES_PROJECT_ADD_CATEGORY_DESCRIPTION": "Crée une nouvelle thématique pour organiser les espaces projets",
    "PLUGINS_WORKSPACES_PROJECT_EDIT_CATEGORY_LABEL": "Modifier",
    "PLUGINS_WORKSPACES_PROJECT_EDIT_CATEGORY_DESCRIPTION": "Modifie les propriétés de la thématique sélectionnée",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_CATEGORY_LABEL": "Supprimer",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_CATEGORY_DESCRIPTION": "Supprimer la thématique sélectionnée",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_CATEGORY_DIALOG_TITLE": "Supprimer la thématique",
    "PLUGINS_WORKSPACES_PROJECT_DELETE_CATEGORY_DIALOG_CONFIRM": "Etes-vous sûr de vouloir supprimer ce ou ces thématiques ? Cela supprimera aussi l'ensemble des projets et thématiques compris dans la sous-arborescence",

    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDIT_DIALOG_TITLE": "Modifier la thématique",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_CREATE_DIALOG_TITLE": "Créer une thématique",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_DIALOG_FORM_TITLE": "Nom",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_DIALOG_FORM_TITLE_DESC": "Nom de la thématique",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_DIALOG_FORM_DESCRIPTION": "Description",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_DIALOG_FORM_DESCRIPTION_DESC": "Description de la thématique",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_DIALOG_OK": "Ok",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_DIALOG_CANCEL": "Annuler",

    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_ERROR_CONFIGURATION": "Opération impossible",
    "PLUGINS_WORKSPACES_PROJECT_CATEGORY_EDITION_ERROR_CONFIGURATION_INCOMPLETE": "Erreur inattendue, les données de configuration sont incomplètes.",

    "PLUGINS_WORKSPACES_PROJECT_MOVE_CATEGORY_LABEL": "Déplacer",
    "PLUGINS_WORKSPACES_PROJECT_MOVE_CATEGORY_DESCRIPTION": "Déplace la thématique sélectionnée dans la hiérarchie des projets.",
    "PLUGINS_WORKSPACES_PROJECT_MOVE_CATEGORY_ERROR": "Une erreur est survenue : la thématique n'a pas été déplacée.",
    "PLUGINS_WORKSPACES_PROJECT_MOVE_CATEGORY_ERROR_INVALID": "La source ou la cible du déplacement n'est pas du type attendu.",
    "PLUGINS_WORKSPACES_PROJECT_MOVE_CATEGORY_ERROR_ALREADY_EXISTS": "Une thématique du même nom est déjà présente au sein de l'objet ciblé.",

    "PLUGINS_WORKSPACES_PROJECT_RELATIONS_CATEGORY_LABEL": "Déplacement d'une thématique",
    "PLUGINS_WORKSPACES_PROJECT_RELATIONS_CATEGORY_DESCRIPTION": "Action de déplacement d'une categorie dans la hiérarchie des espaces projets.",

    "PLUGINS_WORKSPACES_USER_NOTIFICATION_SUCCESS_DEFAULT_TITLE": "",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_SUCCESS_DEFAULT_MESSAGE": "Opération effectuée.",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_SUCCESS_DEFAULT_OK": "OK",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_WARN_DEFAULT_TITLE": "",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_WARN_DEFAULT_MESSAGE": "Attention.",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_WARN_DEFAULT_OK": "OK",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_ERROR_DEFAULT_TITLE": "",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_ERROR_DEFAULT_MESSAGE": "Une erreur est survenue lors d'un échange d'information avec le serveur.",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_ERROR_ACCESS_DENIED_MESSAGE": "Accès refusé : une authentification est requise, ou la cible de la requête n'est pas une cible autorisée.",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_ERROR_DEFAULT_OK": "OK",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_WAIT_DEFAULT_TITLE": "",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_WAIT_DEFAULT_MESSAGE": "Traitement en cours...",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_CONFIRM_DEFAULT_TITLE": "",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_CONFIRM_DEFAULT_MESSAGE": "Veuillez confirmer l'opération.",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_CONFIRM_DEFAULT_OK": "OK",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_CONFIRM_DEFAULT_CANCEL": "Annuler",
    "PLUGINS_WORKSPACES_USER_NOTIFICATION_LOADING_MESSAGE": "Chargement...",

    "PLUGINS_WORKSPACES_USER_NOTIFICATION_ERROR_UNEXPECTED": "Une erreur inattendue est survenue lors de l'échange d'information avec le serveur.",

    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_REQUIRED": "Champ requis",
    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_MINLENGTH": "Valeur trop courte",
    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_MAXLENGTH": "Valeur trop longue",
    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_EMAIL": "E-mail non valide",
    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_NUMBER": "Nombre non valide",
    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_DATE": "Date invalide",
    "PLUGINS_WORKSPACES_FORM_ERRORS_MESSAGE_TIME": "Heure invalide",

    "PLUGINS_WORKSPACES_UNITS_BYTES_BYTE": "o",
    "PLUGINS_WORKSPACES_UNITS_BYTES_KILOBYTE": "ko",
    "PLUGINS_WORKSPACES_UNITS_BYTES_MEGABYTE": "Mo",
    "PLUGINS_WORKSPACES_UNITS_BYTES_GIGABYTE": "Go",
    "PLUGINS_WORKSPACES_UNITS_BYTES_TERABYTE": "To",
    "PLUGINS_WORKSPACES_UNITS_BYTES_PETABYTE": "Po",
    "PLUGINS_WORKSPACES_UNITS_BYTES_EXABYTE": "Eo",
    "PLUGINS_WORKSPACES_UNITS_BYTES_ZETTABYTE": "Zo",
    "PLUGINS_WORKSPACES_UNITS_BYTES_YOTTABYTE": "Yo",

    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_TITLE": "Liste des étiquettes",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_MESSAGE": "Cet outil vous permet de visualiser la liste des étiquettes, de supprimer des étiquettes existantes et d'en créer de nouvelles.",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_ADD_TAG_PLACEHOLDER": "Ajouter une étiquette...",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_ADD_TAG_SUBMIT_LABEL": "Ajouter",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_ADD_TAG_ERROR_EXISTS": "Cette étiquette existe déjà.",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_OK_BUTTON": "OK",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_CANCEL_BUTTON": "Annuler",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_CONFIRM_TITLE": "Modification sur les étiquettes",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_CONFIRM_MSG_INTRO": "Veuillez confirmer les modifications suivantes",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_CONFIRM_MSG_TAGS_ADDED": "Etiquette(s) ajoutée(s)",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_TAGS_CONFIRM_MSG_TAGS_DELETED": "Etiquette(s) supprimée(s)",

    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_TITLE": "Liste des lieux",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_MESSAGE": "Cet outil vous permet de visualiser la liste des lieux, de supprimer des étiquettes lieux et d'en créer de nouveaux.",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_ADD_PLACE_PLACEHOLDER": "Ajouter un lieu...",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_ADD_PLACE_SUBMIT_LABEL": "Ajouter",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_ADD_PLACE_ERROR_EXISTS": "Ce lieu existe déjà.",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_OK_BUTTON": "OK",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_CANCEL_BUTTON": "Annuler",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_CONFIRM_TITLE": "Modification sur les lieux",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_CONFIRM_MSG_INTRO": "Veuillez confirmer les modifications suivantes",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_CONFIRM_MSG_PLACES_ADDED": "Lieu(x) ajouté(s)",
    "PLUGINS_WORKSPACES_PROJECT_MANAGE_PLACES_CONFIRM_MSG_PLACES_DELETED": "Lieu(x) supprimé(s)",

    "PLUGINS_WORKSPACES_WIDGET_DATETIME_CLEAR_TEXT": "Effacer",
    "PLUGINS_WORKSPACES_WIDGET_DATETIME_CLOSE_TEXT": "Fermer",
    "PLUGINS_WORKSPACES_WIDGET_DATETIME_CURRENT_TEXT": "Aujourd'hui",

    "PLUGINS_WORKSPACES_WIDGET_SELECT_NO_RESULTS": "Aucun résultat",
    "PLUGINS_WORKSPACES_WIDGET_SELECT_PLACEHOLDER": "Recherchez dans la liste...",
    "PLUGINS_WORKSPACES_WIDGET_SELECT_NEW_LABEL": "Nouveau",

    "PLUGINS_WORKSPACES_WIDGET_SELECT_PROJECTS_PLACEHOLDER": "Sélectionnez un ou des projets...",

    "PLUGINS_WORKSPACES_SERVICE_CATEGORY_MODULES": "Modules espaces projets",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULES_PARAM_NORIGHT_TEXT": "Lien vers une page",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULES_PARAM_NORIGHT_TEXT_DESC": "Lien vers une page qui sera affiché si l'utilisateur n'a pas le droit de voir le module.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULES_PARAM_NORIGHT_LINK": "Titre du lien",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULES_PARAM_NORIGHT_LINK_DESC": "Titre du lien affiché quand l'utilisateur n'a pas le droit de voir le module.",

    "PLUGINS_WORKSPACES_MODULES_LOADER_DEFAULTTEXT": "Chargement en cours...",
    "PLUGINS_WORKSPACES_MODULES_LOADER_CLOSE": "Fermer",
    "PLUGINS_WORKSPACES_MODULES_ERROR_CLOSE": "Fermer",
    "PLUGINS_WORKSPACES_MODULES_ERROR_DEFAULT": "Une erreur est survenue",
    "PLUGINS_WORKSPACES_MODULES_ERROR_DEFAULT_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste",
    "PLUGINS_WORKSPACES_MODULES_ERROR_FATAL_SERVER_TITLE": "La connexion avec le serveur a été perdue",
    "PLUGINS_WORKSPACES_MODULES_ERROR_FATAL_SERVER_DESCRIPTION": "Cela peut provenir d'un problème de votre connexion au réseau ou d'une opération de maintenance sur le serveur",
    "PLUGINS_WORKSPACES_MODULES_ERROR_FATAL_SESSION_TITLE": "Votre session a expiré",
    "PLUGINS_WORKSPACES_MODULES_ERROR_FATAL_SESSION_DESCRIPTION": "Vous avez été déconnecté et devez recharger la page pour vous connecter à nouveau",
    "PLUGINS_WORKSPACES_MODULES_ERROR_FATAL_RELOAD": "Recharger la page",


    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LABEL": "Calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DESCRIPTION": "Pour communiquer un planning, ou une occupation de salles via un calendrier",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAM_TITLE": "Titre",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAM_TITLE_DESC": "Titre du service",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAM_XSLT": "Affichage",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAM_XSLT_DESC": "Rendu à utiliser pour l'affichage du service.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_XSLT_DEFAULT_LABEL": "Par défaut",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_CALENDAR_TOOLBAR_ARIA_LABEL": "Barre d'outils calendriers",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLBAR_ARIA_LABEL": "Barre d'outils évènements",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_CALENDAR_BUTTON": "Nouveau calendrier",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_CALENDAR_TITLE": "Nouveau calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIRST_CALENDAR_DEFAULT_NAME": "Principal",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_TITLE": "Modifier le calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_OK_BUTTON": "OK",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_CANCEL_BUTTON": "Annuler",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_ERROR_ALREADY_EXIST": "Un calendrier du même nom existe déjà.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_ERROR_LOCKED": "Opération impossible. L'objet parent est verrouillé.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_CALENDAR_CONFIRM_TITLE": "Supprimer le calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_CALENDAR_CONFIRM_MESSAGE": "Veuillez confirmer la suppression du calendrier: &lt;em&gt;{title}&lt;/em&gt;.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_CALENDAR_ERROR_LOCKED": "Suppression impossible. Le calendrier est verrouillé.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_TITLE_LABEL": "Titre",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_DESCRIPTION_LABEL": "Description",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_DESCRIPTION_PLACEHOLDER": "Description du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_COLOR_LABEL": "Couleur",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_COLOR_DESCRIPTION": "Couleur du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_WORKFLOW_LABEL": "Cycle de vie",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_WORKFLOW_DESCRIPTION": "Cycle de vie des évènements",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_TEMPLATE_DESCRIPTION_LABEL": "Modèle de description",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_TEMPLATE_DESCRIPTION_DESCRIPTION": "Le modèle de description des évènements sera automatiquement reporté dans la description des nouveaux évènements.&lt;br&gt;L'auteur de l'évènement aura toujours la possibilité de modifier cette description.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_TEMPLATE_DESCRIPTION_PLACEHOLDER": "Modèle de description pour les évènements.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_VISIBILITY_LABEL": "Visibilité",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_VISIBILITY_DESCRIPTION": "En cochant cette case ce calendrier sera rendu disponible aux webmasters de la plateforme Ametys, pour une éventuelle publication dans un autre site.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_VISIBILITY_PUBLIC_LABEL": "Publiable",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_FIELD_VISIBILITY_PRIVATE_LABEL": "Privé",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_COLOR_PLACEHOLDER": "Sélectionnez ou recherchez une couleur dans la liste...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_CALENDAR_PLACEHOLDER": "Sélectionnez ou recherchez un calendrier dans la liste...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_CALENDARS_PLACEHOLDER": "Sélectionnez ou recherchez des calendriers dans la liste...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_TAGS_PLACEHOLDER": "Recherchez ou créez des étiquettes...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_TAGS_NO_CREATION_PLACEHOLDER": "Recherchez des étiquettes...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_PLACES_PLACEHOLDER": "Recherchez ou créez des lieux...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SELECT_PLACES_NO_CREATION_PLACEHOLDER": "Recherchez des lieux...",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LIST_TITLE": "Calendriers",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LIST_BUTTON": "Calendriers",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SETTINGS_MENU": "Paramètres",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SETTINGS_TAGS_ACTION": "Gérer les étiquettes",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SETTINGS_PLACES_ACTION": "Gérer les lieux",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_CUSTOM_BUTTON_AMETYS_DAY_TEXT": "Jour",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_CUSTOM_BUTTON_AMETYS_WEEK_TEXT": "Semaine",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_CUSTOM_BUTTON_AMETYS_MONTH_TEXT": "Mois",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_MODE_RADIO_AGENDA": "Agenda",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_MODE_RADIO_LIST": "Liste",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ICS_LINK_TITLE": "Lien du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ICS_LINK_FIELD_TITLE": "Lien à utiliser dans votre application de calendrier pour synchronisation",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ICS_LINK_OK_BUTTON": "OK",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ICS_LINK_COPIED": "Le lien a été copié dans votre presse papier",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_EVENT_BUTTON": "Nouvel évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_SHORT_BUTTON": "Modifier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_SHORT_BUTTON": "Supprimer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DUPLICATE_EVENT_SHORT_BUTTON": "Dupliquer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_HANDLE_INVITATION_EVENT_SHORT_BUTTON": "Invitations",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_EVENT_MESSAGING_CONNECTOR_TITLE": "[{0}] {1}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_EVENT_TITLE": "Nouvel évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_TITLE": "Modifier l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_OK_BUTTON": "OK",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_CANCEL_BUTTON": "Annuler",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_ERROR_ALREADY_EXIST": "Un évènement du même nom existe déjà dans ce calendrier.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_CONFIRM_TITLE": "Supprimer l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_ERROR_LOCKED": "Suppression impossible. L'évènement est verrouillé.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_SYNCHRONIZED_UNIT_CONFIRM_WARNING": "Cet évènement est une occurrence d'un évènement récurrent synchronisé avec une messagerie.&lt;br/&gt;Cette suppression ne sera donc pas prise en compte dans la messagerie.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_SYNCHRONIZED_CONFIRM_WARNING": "Cet évènement est synchronisé avec une messagerie. Si vous continuez, il sera supprimé de la messagerie aussi.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_SYNCHRONIZED_ERROR_MSG": "Attention, cet évènement est synchronisé à un évènement de la messagerie qui n'existe plus.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_SYNCHRONIZED_CONFIRM_WARNING_TITLE": "Evènement non synchronisé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_SYNCHRONIZED_CONFIRM_WARNING": "Cet évènement est synchronisé à un évènement de la messagerie qui n'existe plus. Si vous continuez, il sera recréé dans la messagerie.&lt;br/&gt;&lt;br/&gt;Voulez-vous continuer ?",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_SYNCHRONIZED_UNIT_CONFIRM_WARNING_TITLE": "Evènement récurrent synchronisé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_SYNCHRONIZED_UNIT_CONFIRM_WARNING": "Cet évènement est une occurrence d'un évènement récurrent synchronisé avec une messagerie.&lt;br/&gt;Il ne sera donc pas modifié dans la messagerie.&lt;br/&gt;&lt;br/&gt;Voulez-vous continuer ?",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_SYNCHRONIZED_CREATE_CONFIRM_WARNING_MSG": "Cet évènement récurrent va être synchronisé avec la messagerie. Il existe des limitations :&lt;br/&gt;&lt;br/&gt;- La suppression d'une occurrence du côté de la messagerie ne sera pas détectée&lt;br/&gt;- La suppression ou la modification d'une occurrence du côté de l'espace projet ne sera pas prise en compte par la messagerie&lt;br/&gt;- La réponse d'un utilisateur à une occurrence ne pourra pas être récupérée&lt;br/&gt;- La disponibilité ne pourra pas être récupérée&lt;br/&gt;&lt;br/&gt;Voulez-vous continuer ?",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_TITLE_LABEL": "Titre",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_DESCRIPTION_LABEL": "Description",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_DESCRIPTION_PLACEHOLDER": "Description de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_CALENDAR_LABEL": "Calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_CALENDAR_DESCRIPTION": "Calendrier de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_CALENDAR_DESCRIPTION_DESCRIPTION": "Description du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_CALENDAR_DESCRIPTION_NO_DESC": "Ce calendrier ne possède pas de description",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_START_DATE_LABEL": "Date de début",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_START_DATE_DESCRIPTION": "Choix de la date de début de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_END_DATE_LABEL": "Date de fin",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_END_DATE_DESCRIPTION": "Choix de la date de fin de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_END_DATE_BEFORE_START_ERROR": "La date de fin est inférieure à la date de début",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_FULL_DAY_LABEL": "Toute la journée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_RECURRENCE_LABEL": "Récurrence",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_RECURRENCE_DESCRIPTION": "Choix du type de récurrence",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_UNTIL_DATE_LABEL": "Jusqu'à",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_UNTIL_DATE_PLACEHOLDER": "Tout le temps",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_UNTIL_DATE_BEFORE_START_ERROR": "La date est inférieure à la date de début",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_TAGS_LABEL": "Étiquettes",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_TAGS_DESCRIPTION": "Sélection d'étiquettes pour catégoriser l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_PLACES_LABEL": "Lieux",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_PLACES_DESCRIPTION": "Sélection de lieux concernant l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_LABEL": "Gérer les invitations",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_MODAL_TITLE": "Gérer les invitations",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ORGANISER_LABEL": "Organisateur",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ORGANISER_DESCRIPTION": "L'organisateur de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ADD_ALL_BUTTON": "Ajouter tous les membres",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ERROR_ALREADY_EXIST": "{member} a déjà été invité à l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ERROR_IS_ORGANISER": "{member} ne peut pas être ajouté car c'est l'organisateur",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ERROR_EMAIL_INVALID": "{email} n'est pas un email valide",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ERROR_ORGANISER": "{organiser} n'a pas de mail liée au compte de messagerie. Veuillez sélectionner un organisateur valide pour inviter des participants à l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_HINT_ORGANISER": "Veuillez sélectionner un organisateur pour inviter des participants à l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_MEMBERS": "Participants",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_MANDATORY": "Présence obligatoire",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_FREE_BUSY": "Disponibilité",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_STATUS": "Statut",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_OK_BUTTON": "Ok",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_CANCEL_BUTTON": "Annuler",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_FREE_TOOLTIP": "Libre",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_BUSY_TOOLTIP": "Occupé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_UNKNOW_FREE_BUSY_EXTERNAL_TOOLTIP": "Impossible de déterminer la disponibilité d'un utilisateur externe",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_UNKNOW_FREE_BUSY_RECURENT_TOOLTIP": "Impossible de déterminer la disponibilité d'un évènement recurrent",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_UNKNOW_FREE_BUSY_NO_EMAIL_VALID_TOOLTIP": "Impossible de déterminer la disponibilité car l'utilisateur n'a pas d'email lié au compte de messagerie",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_WAITING_TOOLTIP": "En attente de la disponibilité",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ACCEPT_TOOLTIP": "Invitation acceptée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_DECLINE_TOOLTIP": "Invitation refusée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_MAYBE_TOOLTIP": "Peut-être",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_UNKNOW_TOOLTIP": "En attente d'une réponse",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_PLACEHOLDER": "Rechercher un utilisateur ou entrer une adresse mail valide",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_FIELD_HANDLE_INVITATION_ORGANISER_PLACEHOLDER": "Sélectionner un organisateur",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_DATE_FULL_SAME_DAY": "Le {startDate}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_DATE_FULL_DAY": "Du {startDate} au {endDate}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_DATE_ALL_DAY": "Du {startDate} à {startTime} au {endDate} à {endTime}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_DATE_SIMPLE": "Le {startDate} de {startTime} à {endTime}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_RECURRENCE_UNTIL": "Evènement récurrent jusqu'au {untilDate}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_RECURRENCE_ALL_TIME": "Evènement récurrent",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_WORKFLOW": "Etat : {stepLabel}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_CREATED": "Créé le {date} à {time} par {user}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_MODIFIED": "Dernière modification le {date} à {time} par {user}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EVENT_TOOLTIP_VALIDATED": "Dernière validation le {date} à {time} par {user}",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_OK_BUTTON": "OK",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_CANCEL_BUTTON": "Annuler",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_DEFAULT_TITLE": "Opération sur un évènement périodique",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_DEFAULT_MESSAGE": "Souhaitez-vous appliquer l'opération en cours uniquement sur cet évènement ou tous les évènements de la série ?",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_EDIT_TITLE": "Modifier l'évènement périodique",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_DELETE_TITLE": "Supprimer l'évènement périodique",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_MOVE_TITLE": "Déplacer l'évènement périodique",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_UNIT": "Uniquement cet évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_UNIT_DESC": "Les autres évènements de la série resteront identiques.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_ALL": "Tous les évènements",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OCCURRENCE_OPERATION_RANGE_ALL_DESC": "Tous les évènements de la série seront impactés.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OPERATION_RANGE_MOVE_TITLE": "Déplacer l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OPERATION_CANT_MOVE_MESSAGE": "Impossible de déplacer l'évènement, les ressources ne sont pas disponibles aux nouveaux horaires.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_HEADER_TODAY": "Aujourd'hui",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_HEADER_MONTH": "Mois",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_HEADER_WEEK": "Semaine",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_HEADER_DAY": "Jour",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SEE_CALENDAR": "Voir le calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SEE_RESOURCES": "Voir les ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_CALENDAR": "Calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_RESOURCES": "Ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_DUPLICATE_EVENT": "Dupliquer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_DELETE_EVENT": "Supprimer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_EVENT_FROM": "De",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_EVENT_TO": "à",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_EVENT_THE": "le",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_EVENT_UNTIL": "jusqu'au",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_EVENT_FULL_DAY": "Toute la journée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_EVENT_RESOURCES": "Ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_EVENT_PLACE": "Lieu",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_EVENT_TAGS": "Étiquette",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_EVENT_DESCRIPTION": "Description",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_EVENT_CREATOR": "Créateur",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_EVENT_CALENDAR": "Calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_DELETE_EVENT_CONFIRM_TITLE": "Supprimer l'évènement ?",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_SELECTED_DELETE_EVENT_CONFIRM_MESSAGE": "Voulez vous vraiment supprimer 0 ?",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_FILTER": "Filtrer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_HIDE_FILTER": "Masquer les filtres",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_CALENDAR_FILTER_TEXT": "Filtrer par calendrier",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_TITLE": "Lien partageable vers votre agenda",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_TEXT_EXPORTABLE": "Avec ce lien, seules les personnes autorisées peuvent accèder à votre agenda",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_TEXT_NOT_EXPORTABLE": "Vous n'avez pas le droit de partager ce calendrier privé. Veuillez contacter votre chef de projet pour en savoir plus",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_COPY_LINK": "Copier le lien",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_LINK_COPIED": "Copié !",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_CLOSE": "Fermer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EXPORT_CALENDAR_LINK": "Exporter",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NEXT_EVENTS": "Prochains évènements",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NEXT_RESOURCES": "Prochaines réservations",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NO_EVENTS": "Aucun évènement n'a été trouvé",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DATEPICKER_NEXT_DAY": "Aller au jour suivant",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DATEPICKER_MIN": " min",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DATEPICKER_HOUR": " h",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DATEPICKER_HOURS": " h",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DATEPICKER_SEPARATOR": ",",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DATEPICKER_FULL_DAY": "Toute la journée",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_MANDATORY": "Champ obligatoire",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_CALENDAR_TITLE": "Ce champ est limité à 50 caractères",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_CALENDAR_TITLE_EXIST": "Ce nom de calendrier est déjà utilisé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_EVENT_TITLE": "Ce champ est limité à 100 caractères",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_EVENT_DESCRIPTION": "Ce champ est limité à 400 caractères",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_RESOURCE_TITLE": "Ce champ est limité à 50 caractères",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_RESOURCE_TITLE_EXIST": "Ce nom de ressource est déjà utilisé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_RESOURCE_INSTRUCTIONS": "Ce champ est limité à 400 caractères",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_RESOURCE_UNAVAILABLE": "Veuillez selectionner une ressource disponible",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_UNTIL_DATE_BEFORE_END": "La date de fin de répétition ne peut être inférieure à la date de fin de la première occurrence",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FIELD_ERROR_END_DATE_BEFORE_START": "La date de fin ne peut être inférieure à la date de début",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_RESSOURCE_TITLE": "Réserver une ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_BOOK_RESSOURCE_TITLE": "Réserver une ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_DIALOG_BOX_OK": "Valider",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_DIALOG_BOX_CANCEL": "Annuler",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_FIELD_CALENDAR_LABEL": "Afficher la réservation dans un calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_FIELD_NO_CALENDAR_TEXT": "Actuellement, votre réservation ne sera visible que dans la vue des ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_FIELD_TITLE_LABEL": "Titre",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_FIELD_ICON_LABEL": "Icône",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_FIELD_INSTRUCTIONS_LABEL": "Instruction spéciales",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_RESOURCE_TITLE": "Nouvelle ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_TITLE": "Modifier la ressource",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_TITLE": "Gérer les calendriers et les ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_CALENDARS": "Calendriers",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_CALENDARS_SUBTEXT": "Il y a au moins un calendrier par défaut. Vous pouvez ajouter de nouveaux calendriers pour que les utilisateurs associent des évènements à un calendrier spécifique.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_RESOURCES": "Ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_RESOURCES_SUBTEXT": "Ajouter des ressources que les utilisateurs pourront réserver lors d'évènements",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_CREATE_CALENDAR": "Créer un calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_CREATE_RESOURCE": "Créer une ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_CALENDAR": "Supprimer le calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_RESOURCE": "Supprimer la ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_EDIT_BUTTON": "Modifier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_BUTTON": "Supprimer",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_CONFIRM_MESSAGE": "Voulez vous vraiment supprimer 0 ? 1",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_CANT_DELETE_LAST_CALENDAR_MESSAGE": "Impossible de supprimer ce calendrier, il doit toujours y avoir au moins un calendrier.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_CONFIRM_MESSAGE_CALENDAR_TEXT": "Tous les évènements qu'il contient seront supprimés.",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_PARAMETERS_DIALOG_DELETE_CONFIRM_MESSAGE_RESOURCE_TEXT": "Cette ressource sera retirée des évènements qui l'utilisent.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_TOOLBAR_CALENDARS": "Calendriers",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_TOOLBAR_ALL_CALENDARS": "Voir tous les calendriers",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_TOOLBAR_NO_CALENDAR": "Hors calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_TOOLBAR_RESOURCE_CALENDAR": "Réservations sans calendrier",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_GENERAL_ERROR_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste.",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_CALENDAR_BEGIN_MSG": "Création du calendrier en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_BEGIN_MSG": "Modification du calendrier en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_CALENDAR_BEGIN_MSG": "Suppression du calendrier en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_CALENDAR_END_MSG": "Le calendrier a été créé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_END_MSG": "Le calendrier a été modifié",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_CALENDAR_END_MSG": "Le calendrier a été supprimé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_CALENDAR_ERROR_MSG": "Une erreur est survenue lors de la création du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_CALENDAR_ERROR_MSG": "Une erreur est survenue lors de la modification du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_CALENDAR_ERROR_MSG": "Une erreur est survenue lors de la suppression du calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_CALENDAR_ERROR_MSG": "Une erreur est survenue lors du chargement des calendriers",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_RECURRING_ERROR_MSG": "Une erreur est survenue lors du chargement des éléments récurrents",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_TAGS_ERROR_MSG": "Une erreur est survenue lors du chargement des étiquettes",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_COLORS_ERROR_MSG": "Une erreur est survenue lors du chargement des couleurs",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_EVENT_BEGIN_MSG": "Création de l'évènement en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_BEGIN_MSG": "Modification de l'évènement en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_BEGIN_MSG": "Suppression de l'évènement en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_EVENT_END_MSG": "L'évènement a été créé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_END_MSG": "L'évènement a été modifié",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_END_MSG": "L'évènement a été supprimé",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_EVENT_ERROR_MSG": "Une erreur est survenue lors de la création de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_EVENT_ERROR_MSG": "Une erreur est survenue lors de la modification de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_EVENT_ERROR_MSG": "Une erreur est survenue lors de la suppression de l'évènement",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_EVENT_ERROR_MSG": "Une erreur est survenue lors du chargement des évènements",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_RESOURCE_BEGIN_MSG": "Création de la ressource en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_BEGIN_MSG": "Modification de la ressource en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_RESOURCE_BEGIN_MSG": "Suppression de la ressource en cours",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_RESOURCE_END_MSG": "La ressource a été créée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_END_MSG": "La ressource  a été modifiée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_RESOURCE_END_MSG": "La ressource a été supprimée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ADD_RESOURCE_ERROR_MSG": "Une erreur est survenue lors de la création de la ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_RESOURCE_ERROR_MSG": "Une erreur est survenue lors du chargement des ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_EDIT_RESOURCE_ERROR_MSG": "Une erreur est survenue lors de la modification de la ressource",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_DELETE_RESOURCE_ERROR_MSG": "Une erreur est survenue lors de la suppression de la ressource",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_LOAD_USER_ERROR_MSG": "Une erreur est survenue lors du chargement de l'utilisateur",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FULL_DAY_DATE_FORMAT": "dddd Do MMMM",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SEE_CALENDAR": "Voir le calendrier",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_SEE_RESOURCES": "Voir les ressources",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NEW": "Nouveau",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NO_DATA_AVAILABLE_ICON": "Aucune icône disponible",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NO_DATA_AVAILABLE_RESOURCE": "Aucune ressource disponible",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_NO_DATA_AVAILABLE_CALENDAR": "Aucun calendrier disponible",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_ICON_SELECTED": "1 icône sélectionnée",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_FAVORITE_ICONS": "Favoris",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_OTHER_ICONS": "Autres",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_AVAILABLE_RESOURCE": "Disponible",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_UNAVAILABLE_RESOURCE": "Non disponible",

    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_LABEL": "Répétition",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_DESC": "Choisir la périodicité de l'évènement",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_NEVER": "Jamais",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_ALL_DAY": "Tous les jours",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_ALL_WORKING_DAY": "Tous les jours ouvrables",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_WEEKLY": "Hebdomadaire",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_BIWEEKLY": "Toutes les deux semaines",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_MONTHLY": "Mensuelle",
    "PLUGINS_WORKSPACES_EVENT_LIST_PERIOD_UNTIL": "Jusqu'au",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_WORKFLOW_MENU_LABEL_BUTTON_TEXT": "Cycle de vie : ",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_WORKFLOW_MENU_LOADING_LABEL": "Chargement...",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_MODULE_CALENDAR_WORKFLOW_MENU_DISABLED_DESCRIPTION": "Cette action n'est pas disponible car vous n'avez pas les droits suffisants ou que les conditions requises ne sont pas remplies.",

    "WORKFLOW_CALENDAR_STATE_DRAFT": "Brouillon",
    "WORKFLOW_CALENDAR_STATE_DRAFT_DESCRIPTION": "L'état 'Brouillon' est activé lorsque l'évènement sélectionné est dans un tel état.",
    "WORKFLOW_CALENDAR_STATE_PROPOSED": "Proposé",
    "WORKFLOW_CALENDAR_STATE_PROPOSED_DESCRIPTION": "L'état 'Proposé' est activé lorsque l'évènement sélectionné est dans un tel état.",
    "WORKFLOW_CALENDAR_STATE_VALIDATED": "Validé",
    "WORKFLOW_CALENDAR_STATE_VALIDATED_DESCRIPTION": "L'état 'Validé' est activé lorsque l'évènement sélectionné est dans un tel état.",

    "WORKFLOW_CALENDAR_ACTION_EDIT": "Modification",
    "WORKFLOW_CALENDAR_ACTION_EDIT_DESCRIPTION": "Action de modification de l'évènement sélectionné.",
    "WORKFLOW_CALENDAR_ACTION_PROPOSE": "Proposition",
    "WORKFLOW_CALENDAR_ACTION_PROPOSE_DESCRIPTION": "Action de proposition de l'évènement sélectionné afin qu'il soit validé.",
    "WORKFLOW_CALENDAR_ACTION_VALIDATE": "Validation",
    "WORKFLOW_CALENDAR_ACTION_VALIDATE_DESCRIPTION": "Action de validation de l'évènement sélectionné.",
    "WORKFLOW_CALENDAR_ACTION_REFUSE": "Refus",
    "WORKFLOW_CALENDAR_ACTION_REFUSE_DESCRIPTION": "Action de refus de l'évènement sélectionné.",

    "PLUGINS_WORKSPACES_SERVICE_TASKS_SETTINGS_DIALOG_TITLE": "Paramètres",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_LABEL": "Calendrier des espaces projets",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_DESCRIPTION": "Prochains évènements des calendriers des espaces projets.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_TITLE": "Titre du service",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_TITLE_DESC": "Titre du service (Exemple : \"Mes prochains évènements\").",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_MAX_RESULTS": "Nombre de résultats max",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_MAX_RESULTS_DESC": "Nombre maximum d'évènements à afficher.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_RESULTS_PER_PAGE": "Nombre de résultats par page",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_RESULTS_PER_PAGE_DESC": "Nombre d'évènements à afficher par page en mode liste.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SEARCH_PERIOD": "Période de recherche (en mois)",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SEARCH_PERIOD_DESC": "Période sur laquelle s'étale la recherche des prochains évènements.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_ENABLE_CREATION": "Création d'évènements",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_ENABLE_CREATION_DESC": "Permet d'afficher un bouton pour créer un nouvel évènement depuis le service.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_EVENT_CREATION_TEXT": "Texte du bouton de création",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_EVENT_CREATION_TEXT_DESC": "Texte à afficher sur le bouton de création d'un nouvel évènement.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_EVENT_CREATION_TEXT_DEFAULT_VALUE": "Nouvel évènement",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_PARAM_XSLT": "Affichage",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_PARAM_XSLT_DESC": "Rendu à utiliser pour l'affichage du service.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_XSLT_DEFAULT_LABEL": "Par défaut",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_TITLE": "Paramètres",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_TODAY_TITLE": "Aujourd'hui",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_DIALOG_TITLE": "Paramètres",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_VIEW": "Affichage",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_VIEW_DESC": "Sélection du mode d'affichage des évènements.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_VIEW_CALENDAR": "Calendrier",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_VIEW_LIST": "Liste",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_CALENDARS": "Calendriers",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_CALENDARS_DESC": "Calendriers à utiliser pour la recherche des évènements à afficher.",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_ALL_CALENDARS": "- Tous les calendriers -",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_TAGS": "Etiquettes",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_FIELD_TAGS_DESC": "Les évènements affichés auront au moins une de ces étiquettes.",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_OK_BTN": "Ok",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_SETTINGS_FORM_CANCEL_BTN": "Annuler",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_AT": "à",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_THE": "Le",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_FROM": "Du",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_FROM_2": "De",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_TO": "au",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_TO_2": "à",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_ALL_DAY": "toute la journée",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_ALL_DAY_2": "Toute la journée",

    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_MONTH_EVENT": "évènement ce mois-ci",
    "PLUGINS_WORKSPACES_SERVICE_FILTERED_EVENTS_MONTH_EVENTS": "évènements ce mois-ci",

    "PLUGINS_WORKSPACES_MODULE_UPLOAD_ERROR_TOOBIG_TITLE": "Taille maximale dépassée",

    "PLUGINS_WORKSPACES_CATALOGUE_GOTOCMS": "Gérer dans le backoffice",

    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT": "Supprimer le projet",
    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT_CONFIRMATION_TITLE": "Supprimer le projet",
    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT_CONFIRMATION_BUTTON": "Supprimer",
    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT_RUNNING": "Suppression en cours...",
    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT_DONE": "Le projet a été supprimé",
    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT_FAIL": "Une erreur est survenue lors de la suppression du projet",
    "PLUGINS_WORKSPACES_CATALOGUE_DELETEPROJECT_FAIL_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste",

    "PLUGINS_WORKSPACES_CATALOGUE_EDITPROJECT": "Modifer le projet",
    "PLUGINS_WORKSPACES_CATALOGUE_EDITPROJECTDIALOG_TITLE": "Modifier le projet",

    "PLUGINS_WORKSPACES_CATALOGUE_EDITPROJECT_RUNNING": "Modification en cours...",
    "PLUGINS_WORKSPACES_CATALOGUE_EDITPROJECT_DONE": "Le projet a été modifié",
    "PLUGINS_WORKSPACES_CATALOGUE_EDITPROJECT_FAIL": "La modification du projet a échoué",
    "PLUGINS_WORKSPACES_CATALOGUE_EDITPROJECT_FAIL_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste",

    "PLUGINS_WORKSPACES_CATALOGUE_LOADPROJECT_FAIL": "Le chargement de vos projets a échoué",
    "PLUGINS_WORKSPACES_CATALOGUE_LOADPROJECT_FAIL_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste",
    "PLUGINS_WORKSPACES_CATALOGUE_LOADKEYWORDS_FAIL": "Le chargement des mots-clefs des projets a échoué",
    "PLUGINS_WORKSPACES_CATALOGUE_LOADKEYWORDS_FAIL_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste",

    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECT_RUNNING": "Création en cours...",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECT_DONE": "Le projet a été créé.",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECT_DONEREDIRECTION": "Le projet a été créé. Redirection vers le nouveau projet...",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECT_FAIL": "La création du projet a échoué",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECT_FAIL_TEXT": "Veuillez réessayer plus tard ou contacter l'administrateur si l'erreur persiste",

    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECT": "Nouveau projet",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_TITLE": "Créer un nouveau projet",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_VALIDATE": "Valider",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_OPTIONS": "Autres options",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_TITLE": "Titre",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_DESCRIPTION": "Description",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_ILLUSTRATION": "Illustration",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_CATEGORY": "Thématique",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_KEYWORDS": "Mots-clés",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_KEYWORDS_HINT1": "Le mot-clé",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_KEYWORDS_HINT2": "n'existe pas.",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_KEYWORDS_HINT3": "Appuyez sur &lt;kbd&gt;Entrée&lt;/kbd&gt; pour ajouter celui-ci à la liste des mot-clés.",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_VISIBILITY": "Visibilité",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_VISIBILITY_PRIVATE": "Projet privé sur invitation uniquement",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_VISIBILITY_PUBLIC_MODERATED": "Projet public avec inscription modérées par le(s) responsable(s)",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_VISIBILITY_PUBLIC_OPENED": "Projet public et ouvert à tous les utilisateurs de la plateforme",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODEL_DEFAULTPROFILE": "Profil des membres lors de l'inscription",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODELADVANCED": "Paramètres avancés",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODELADVANCED_LANGUAGE": "Langue",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODELADVANCED_MANAGERS": "Responsable(s)",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_FIELD_ERROR_MANDATORY": "Champ obligatoire",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_TITLE_FIELD_ERROR_MAX_LENGTH": "Ce champ est limité à 100 caractères",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_DESCRIPTION_FIELD_ERROR_MAX_LENGTH": "Ce champ est limité à 400 caractères",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_PRIVATE_HINT": "Projet privé sur invitation uniquement.",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_MODERATE_HINT": "Projet public avec inscriptions modérées par le(s) responsable(s).",
    "PLUGINS_WORKSPACES_CATALOGUE_NEWPROJECTDIALOG_OPENED_HINT": "Projet public ouvert à tous les utilisateurs de la plateforme.",

    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_TAGS_EMPTY_TEXT": "Aucune étiquette",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_TAGS_BUTTON_TOOLTIP": "Sélectionnez une ou plusieurs étiquettes",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_TAGS_DIALOG_TITLE": "Étiquettes",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_TAGS_DIALOG_HINT": "Sélectionnez une ou plusieurs étiquettes dans la liste des étiquettes.",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_TAGS_DIALOG_NO_TAG_FOUND": "Aucune étiquette n'a été définie. Contactez votre administrateur pour créer de nouvelles étiquettes.",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_CATEGORIES_EMPTY_TEXT": "Aucune thématique",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_CATEGORIES_BUTTON_TOOLTIP": "Sélectionnez une ou plusieurs thématiques",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_CATEGORIES_DIALOG_TITLE": "Thématiques",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_CATEGORIES_DIALOG_HINT": "Sélectionnez une ou plusieurs thématiques dans la liste des thématiques.",
    "PLUGINS_WORKSPACES_WIDGET_TREESELECT_CATEGORIES_DIALOG_NO_TAG_FOUND": "Aucune thématique n'a été définie. Contactez votre administrateur pour créer de nouvelles thématiques.",
    "PLUGINS_WORKSPACES_WIDGET_SELECTTREE_MODAL_OK_BUTTON": "Valider",
    "PLUGINS_WORKSPACES_WIDGET_SELECTTREE_MODAL_CANCEL_BUTTON": "Annuler",

    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_LABEL": "Flux d'activités",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_DESCRIPTION": "Service affichant les activités des membres d'un ou plusieurs espaces projets",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_TITLE": "Titre",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_TITLE_DESC": "Titre à afficher pour le service",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_ACTIVITIES_PER_PAGE": "Activités par page",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_ACTIVITIES_PER_PAGE_DESC": "Nombre d'activités à afficher par page",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_MAX_ACTIVITIES": "Activités max.",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_MAX_ACTIVITIES_DESC": "Nombre maximal d'activités à afficher",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_CHRONOLOGICAL_ORDER": "Ordre chronologique",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_CHRONOLOGICAL_ORDER_DESC": "Cochez cette case si vous souhaitez afficher les évènements les plus vieux en premier",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_XSLT": "Affichage",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_PARAM_XSLT_DESC": "Rendu à utiliser pour l'affichage du service",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_XSLT_DEFAULT_LABEL": "Par défaut",

    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_BTN_TITLE": "Paramètres",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_DIALOG_TITLE": "Paramètres",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_ALL_PROJECTS": "- Tous les projets -",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_FORM_FIELD_PROJECT": "Projets",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_FORM_FIELD_PROJECT_DESC": "Sélection des projets à partir desquels récupérer les activités à afficher",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_FORM_FIELD_ACTIVITY_TYPE": "Sélectionnez ci-après les types d'évènements que vous souhaitez voir dans votre flux d'activité",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_FORM_FIELD_ACTIVITY_TYPE_DESC": "Sélection des types d'activités à afficher dans le service",

    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_FORM_FIELD_ACTIVITY_TYPE_TABLE_MODULE_ACTION": "Evénements",
    "PLUGINS_WORKSPACES_SERVICE_ACTIVITY_STREAM_SETTINGS_FORM_FIELD_ACTIVITY_TYPE_TABLE_ACTIVATE": "Activer",

    "PLUGINS_WORKSPACES_EVENT_TYPE_RESOURCE_CREATED": "Document créé",
    "PLUGINS_WORKSPACES_EVENT_TYPE_RESOURCE_UPDATED": "Document mis à jour",
    "PLUGINS_WORKSPACES_EVENT_TYPE_RESOURCE_RENAMED": "Document renommé",

    "PLUGINS_WORKSPACES_EVENT_TYPE_THREAD_CREATED": "Nouveau fil de discussion",
    "PLUGINS_WORKSPACES_EVENT_TYPE_POST_CREATED": "Nouveau message",

    "PLUGINS_WORKSPACES_EVENT_TYPE_CALENDAR_EVENT_CREATED": "Nouvel évènement",
    "PLUGINS_WORKSPACES_EVENT_TYPE_CALENDAR_EVENT_UPDATED": "Evénement mis à jour",

    "PLUGINS_WORKSPACES_EVENT_TYPE_MEMBER_ADDED": "Nouveau membre",

    "PLUGINS_WORKSPACES_EVENT_TYPE_PAGE_ADDED": "Nouvelle page",
    "PLUGINS_WORKSPACES_EVENT_TYPE_PAGE_UPDATED": "Page mise à jour",

    "PLUGINS_WORKSPACES_EVENT_TYPE_TASK_CREATED": "Nouvelle tâche",
    "PLUGINS_WORKSPACES_EVENT_TYPE_TASK_ASSIGNED": "Nouvelle affectation",
    "PLUGINS_WORKSPACES_EVENT_TYPE_TASK_CLOSED_STATUS_CHANGED": "Statut de fermeture mis à jour",

    "PLUGINS_WORKSPACES_EVENT_TYPE_WALL_CONTENT_CREATED": "Nouvelle brève",
    "PLUGINS_WORKSPACES_EVENT_TYPE_NEWS_PUBLISHED": "Nouvelle actualité",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_PROJECT_ACTIVITIES": "Projets ",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_ALL_LABEL": "Tous",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_DOCUMENTS_LABEL": "Documents",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_CALENDARS_LABEL": "Calendriers",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_THREADS_LABEL": "Discussions",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_PROJECTS_LABEL": "Projets",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_MINISITE_LABEL": "Mini-site",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_TASKS_LABEL": "Tâches",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_THE": "Le",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_AT": "à",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_AND": "et",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_BETWEEN": "entre",

    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_ADDED_DESC": "{author} a ajouté l'évènement {event} dans le calendrier {calendar}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_ADDED_WITH_PROJECT_DESC": "{author} a ajouté l'évènement {event} dans le calendrier {calendar} du projet {project}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_UPDATED_DESC": "{author} a mis à jour l'évènement {event} du calendrier {calendar}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_UPDATED_WITH_PROJECT_DESC": "{author} a mis à jour l'évènement {event} du calendrier {calendar} du projet {project}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_ADDED_MULTI_DESC": "{author} a ajouté les évènements {events} dans le calendrier {calendar}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_ADDED_MULTI_WITH_PROJECT_DESC": "{author} a ajouté les évènements {events} dans le calendrier {calendar} du projet {project}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_UPDATED_MULTI_DESC": "{author} a mis à jour les évènements {events} du calendrier {calendar}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_EVENT_CALENDAR_UPDATED_MULTI_WITH_PROJECT_DESC": "{author} a mis à jour les évènements {events} du calendrier {calendar} du projet {project}",
    "PLUGINS_WORKSPACES_PROJECT_SERVICE_ACTIVITY_STREAM_SEE_EVENT": "Voir l'évènement",


    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_LABEL": "Calendrier des espaces projets (simple)",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_DESCRIPTION": "Prochains évènements des calendriers des espaces projets (version basique).",

    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_HEADER": "Titre",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_HEADER_DESC": "Titre du service (Exemple : \"Mes prochains évènements\").",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_MAX_RESULTS": "Nombre de résultats maximum",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_MAX_RESULTS_DESC": "Nombre maximum d'évènements à afficher. Laisser vide pour ne pas avoir de limite.",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_SEARCH_PERIOD": "Période de recherche (en mois)",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_SEARCH_PERIOD_DESC": "Période sur laquelle s'étale la recherche des prochains évènements.",

    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_PARAM_XSLT": "Affichage",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_PARAM_XSLT_DESC": "Rendu à utiliser pour l'affichage du service.",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_XSLT_DEFAULT_LABEL": "Par défaut",

    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_NO_RESULTS": "Aucun évènement sur la période définie.",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_DATE_FORMAT": "dd MMM yyyy",
    "PLUGINS_WORKSPACES_SERVICE_SIMPLE_FILTERED_EVENTS_TIME_FORMAT": "HH:mm",

     // TAGS
    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_JCR_LABEL": "Etiquettes",
    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_JCR_DESCRIPTION": "Les étiquettes sont éditables : vous pouvez créer / modifier ou supprimer des étiquettes pour les projets.",
    "PLUGINS_WORKSPACES_UITOOL_TAGS_LABEL": "Etiquettes",
    "PLUGINS_WORKSPACES_UITOOL_TAGS_DESC": "Gestion des étiquettes des projets",

     // CATEGORIES
    "PLUGINS_WORKSPACES_CATEGORIES_CATEGORYPROVIDER_JCR_LABEL": "Thématiques",
    "PLUGINS_WORKSPACES_CATEGORIES_CATEGORYPROVIDER_JCR_DESCRIPTION": "Les thématiques sont éditables : vous pouvez créer / modifier ou supprimer des thématiques pour les projets.",
    "PLUGINS_WORKSPACES_CATEGORIES_TEMPLATE_TOOLTIP_COLOR": "Couleur",

    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_CATEGORY_LABEL": "Espaces projets - Thématiques",
    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_CATEGORY_DESCRIPTION": "Les étiquettes de cette catégorie représentent les thématiques de projets existantes.",

    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_KEYWORD_LABEL": "Espace projets - Mots clés",
    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_KEYWORD_DESCRIPTION": "Les étiquettes de cette catégorie représentent les mots clés de projets existants.",

    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_TAG_LABEL": "Espace projets - Etiquettes",
    "PLUGINS_WORKSPACES_TAGS_TAGPROVIDER_TAG_DESCRIPTION": "Les étiquettes de cette catégorie représentent les étiquettes utilisées dans les modules des projets.",

    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_LABEL": "Thématiques",
    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_DESC": "Gestion des thématiques de projet",
    "PLUGINS_WORKSPACES_FORM_CATEGORY_COLOR_LABEL": "Couleur",
    "PLUGINS_WORKSPACES_FORM_CATEGORY_COLOR_DESC": "Couleur de la thématique",
    "PLUGINS_WORKSPACES_CATEGORIES_ROOT_NODE_LABEL": "Thématiques",

    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_ADD_CATEGORY_LABEL": "Ajouter une thématique",
    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_ADD_CATEGORY_DESC": "Ajouter une thématique",
    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_EDIT_CATEGORY_LABEL": "Modifier la thématique",
    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_EDIT_CATEGORY_DESC": "Modifier la thématique",
    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_DELETE_CATEGORY_LABEL": "Supprimer la thématique",
    "PLUGINS_WORKSPACES_UITOOL_CATEGORIES_DELETE_CATEGORY_DESC": "Supprimer la thématique",

    "PLUGINS_WORKSPACES_DIALOGBOX_CATEGORIES_ADD_LABEL": "Ajouter une thématique",
    "PLUGINS_WORKSPACES_DIALOGBOX_CATEGORIES_EDIT_LABEL": "Modifier une thématique",
    "PLUGINS_WORKSPACES_DIALOGBOX_CATEGORIES_REMOVE_LABEL": "Supprimer une thématique",
    "PLUGINS_WORKSPACES_DIALOGBOX_CATEGORIES_REMOVE_DESC": "Etes-vous sûr de vouloir supprimer cette thématique ?",

    // KEYWORDS

    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_LABEL": "Mots-Clés",
    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_DESC": "Gestion des mots-clés des projets",
    "PLUGINS_WORKSPACES_KEYWORDS_ROOT_NODE_LABEL": "Mots-Clés",

    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_ADD_KEYWORD_LABEL": "Ajouter un mot-clé",
    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_ADD_KEYWORD_DESC": "Ajouter un mot-clé",
    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_EDIT_KEYWORD_LABEL": "Modifier le mot-clé",
    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_EDIT_KEYWORD_DESC": "Modifier le mot-clé",
    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_DELETE_KEYWORD_LABEL": "Supprimer le mot-clé",
    "PLUGINS_WORKSPACES_UITOOL_KEYWORDS_DELETE_KEYWORD_DESC": "Supprimer le mot-clé",

    "PLUGINS_WORKSPACES_KEYWORDS_KEYWORDPROVIDER_JCR_LABEL": "Mots-Clés",
    "PLUGINS_WORKSPACES_KEYWORDS_KEYWORDPROVIDER_JCR_DESCRIPTION": "Les mots-clés sont éditables : vous pouvez créer / modifier ou supprimer des mots-clés pour les projets",

    "PLUGINS_WORKSPACES_DIALOGBOX_KEYWORDS_ADD_LABEL": "Ajouter un mot-clé",
    "PLUGINS_WORKSPACES_DIALOGBOX_KEYWORDS_EDIT_LABEL": "Modifier un mot-clé",
    "PLUGINS_WORKSPACES_DIALOGBOX_KEYWORDS_REMOVE_LABEL": "Supprimer un mot-clé",
    "PLUGINS_WORKSPACES_DIALOGBOX_KEYWORDS_REMOVE_DESC": "Etes-vous sûr de vouloir supprimer ce mot-clé ?",


    // Format Date
    "PLUGINS_WORKSPACES_DATE_DURATION_MINUTES": "min",
    "PLUGINS_WORKSPACES_DATE_DURATION_HOURS": "h",
    "PLUGINS_WORKSPACES_DATE_FORMAT_YESTERDAY": "[hier, ]HH[h]mm",
    "PLUGINS_WORKSPACES_DATE_FORMAT": "[le] Do MMMM",
    "PLUGINS_WORKSPACES_DATE_FORMAT_WITH_YEAR": "[le] Do MMMM YYYY",
    "PLUGINS_WORKSPACES_DATE_TIME_FORMAT": "[le] Do MMMM [à] HH[h]mm",
    "PLUGINS_WORKSPACES_DATE_TIME_FORMAT_WITH_YEAR": "[le] Do MMMM YYYY [à] HH[h]mm",

}
</script>
